# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef28176441e2131a5087b787b4b8853c2c61789e10cb3f045f674dbb96e4bc56c8d8a0b107c83fe4bb7b4cfd140674789ebe75b5678d7f06c0be78ed155d1665

test:
  secret_key_base: 81017a66443f9a63d3aee1e8a4c8083af8b9248d8e1fd2efa018228f79f2566e7c5cfe7bd670f328f2d8d38108306fba6c5f53637fe1a074a5217e73cd167a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
